### ISSUE TITLE
check if arg model is a model

### ISSUE THREAD

**Issue by lilymedina** [macartan/CausalQueries#129]

**Comment by lilymedina** [comment]
use class(model) = "causal_model"

and perhaps check if it has a dag df

**Comment by lilymedina** [comment]
@juliosolisar you were working on this issue, right?

**Comment by lilymedina** [comment]
Just assign yourself in case you're

I didn't mean to put pressure

**Comment by juliosolisar** [comment]
😆😆😆. Just assigned myself. 

Tried the [checkmate](https://cran.r-project.org/web/packages/checkmate/vignettes/checkmate.html) approach but made the package go beserk, so will do the one liner as you suggest.

**Comment by lilymedina** [comment]
Addressed in PR #201
