### ISSUE TITLE
error in causalmodels

### ISSUE THREAD

**Issue by macartan** [macartan/CausalQueries#193]
I am trying to update https://macartan.github.io/causalmodels/ but running into issues here:

```
> updated2 <- update_model(model, df_open_door_large)
Error in unserialize(socklist[[n]]) : error reading from connection
Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection
```
Any sense what this is?

@juliosolisar could you have a go at updating the doc? with do_diagnosis = TRUE

**Comment by juliosolisar** [comment]
Taking a look today

**Comment by macartan** [comment]
not sure if this helps:
https://discourse.mc-stan.org/t/error-in-unserialize-socklist-n-error-reading-from-connection-error-in-serialize-data-node-con-xdr-false-error-writing-to-connection/7614/46

note that his model might no be identified
worth checking on one chain first

**Comment by macartan** [comment]
any luck with this?
@Lily Medina <lilymiru@gmail.com> any thoughts?

**Comment by lilymedina** [comment]
@macartan can you share the lines of code for the model?

**Comment by lilymedina** [comment]
has this error been fixed? My understanding is that the guide is compiling again. If so this issue can be closed. 

I haven't got access to the guide's repository yet so can't check. 

Let me know

**Comment by juliosolisar** [comment]
Thanks for the note @lilymedina. This is working, closing issue
