### ISSUE TITLE
update_model object 'stanmodels' not found

### ISSUE THREAD

**Issue by jonfoong** [macartan/CausalQueries#215]
I'm using the development version of CQ but I face the same issue with the CRAN version.

The update_model function calls an within the function called stanmodels that doesn't exist. Eventually the function returns a model object that is the same as the input model. 

`stanfit <- stanmodels$simplexes`

**Comment by macartan** [comment]
it exists but is not exported; 
try:

`CausalQueries:::stanmodels$simplexes`

```

```
