### ISSUE TITLE
need warning for improper model

### ISSUE THREAD

**Issue by macartan** [macartan/CausalQueries#41]
this model crashes stan:
note that the attempt to set a confound duplicates "M" rows with confounding behavior that depends on X, which is prior to M.

```
model <- make_model("X -> M -> Y")  %>%
          set_confound(confound = list(M = "Y[X=1]==1")) 
data <- draw_data(model)
gbiqq(model, stan)
```

can we figure out the reason for crashing (related to bad simplices) and give a useful message

**Comment by macartan** [comment]
problem with models structure should be spotted by make_confounds_df

issue here is that Y[X=1]==1 deends on M's type, but assignment of M cannot be conditional on M

**Comment by lilymedina** [comment]
A way to check whether a confound induces a structural error in the model is to see if the sum of `w` or `prob_of_types` is different from 1, and throw a general  error message if that happens.


```
model <- make_model(" X -> M -> Y ")  %>%
	set_confound(confound = list(M = "Y[X=1]==1")) 


P <-  model$P
A <- get_ambiguities_matrix(model)
param <- get_param_dist(model, n_draws = 1, using = "priors")
P.lambdas <- P*param 
P.lambdas <- P.lambdas +	1 - P 
prob_of_types <-  apply(P.lambdas, 2, prod)
sum(prob_of_types)
[1] 1.068888
w <- t(A) %*% prob_of_types
sum(w)
[1] 1.068888
```

It would be great to directly observe this from P. But I don't think that's possible.

Any other suggestion?

**Comment by lilymedina** [comment]
I'll go ahead and implement this solution

**Comment by lilymedina** [comment]
Code below also outputs a corrupted model
```
model <- make_model("X -> Y <- M")   %>%
  set_confound(confound = list(M = "Y[X=1]==1")) 
update_model(model, simulate_data(model))
```
Issue here is that assignment of M depends on X through Y.  

PR'ing a solution for this that returns an unaltered model and warning `"Cannot characterize confounding; no action taken"`. I'd love to be more  informative but don't know how to spot all the cases for which this issue might arise.
